version: '3.7'
services:
    node:
        build: .
        container_name: "node"
        ports:
            - "8080:8080"
        depends_on:
            - mongo
        links:
            - mongo
    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        logging:
            driver: none
        restart: always
        volumes:
            - mongodb:/data/db
volumes:
    mongodb:

        
